pipeline {
    agent{
        label 'ansible-master'
    }
    stages {
        stage('Check working directory') {
            steps {
                sh 'pwd'
                sh 'ls'
            }
        }
    }
}
