pipeline {
    agent{
        label 'ansible-master'
    }
    stages {
        stage('Check working dir') {
            steps {
                sh 'pwd'
                sh 'ls -a'
            }
        }  
        stage('Create zip file') {
            steps {
                sh 'wget https://github.com/gad0788/ansible-dev1/archive/refs/heads/main.zip'
               
            }
        }
        stage('Delete old artifacts if exist'){
         steps{
          sh 'rm -rf *.zip || echo "" '
          }
        }
    }
}